dotfiles_source:
  - .exports
  - .path
  - .selected_editor
dotfiles_no_source:
  - .gitconfig
  - .npmrc
dotfiles_all: "{{ dotfiles_source + dotfiles_no_source }}"
home_folder: "{{ lookup('ansible.builtin.env', 'HOME') }}"
repo_dir: "{{ lookup('ansible.builtin.env', 'PWD') }}"
